package cn.iocoder.yudao.module.system.controller.admin.oauth2;

import cn.hutool.core.lang.Assert;
import cn.hutool.core.util.ArrayUtil;
import cn.hutool.core.util.ObjectUtil;
import cn.hutool.core.util.StrUtil;
import cn.iocoder.yudao.framework.common.enums.UserTypeEnum;
import cn.iocoder.yudao.framework.common.pojo.CommonResult;
import cn.iocoder.yudao.framework.common.util.http.HttpUtils;
import cn.iocoder.yudao.framework.common.util.json.JsonUtils;
import cn.iocoder.yudao.module.system.controller.admin.oauth2.vo.open.OAuth2OpenAccessTokenRespVO;
import cn.iocoder.yudao.module.system.controller.admin.oauth2.vo.open.OAuth2OpenAuthorizeInfoRespVO;
import cn.iocoder.yudao.module.system.controller.admin.oauth2.vo.open.OAuth2OpenCheckTokenRespVO;
import cn.iocoder.yudao.module.system.convert.oauth2.OAuth2OpenConvert;
import cn.iocoder.yudao.module.system.dal.dataobject.oauth2.OAuth2AccessTokenDO;
import cn.iocoder.yudao.module.system.dal.dataobject.oauth2.OAuth2ApproveDO;
import cn.iocoder.yudao.module.system.dal.dataobject.oauth2.OAuth2ClientDO;
import cn.iocoder.yudao.module.system.enums.oauth2.OAuth2GrantTypeEnum;
import cn.iocoder.yudao.module.system.service.oauth2.OAuth2ApproveService;
import cn.iocoder.yudao.module.system.service.oauth2.OAuth2ClientService;
import cn.iocoder.yudao.module.system.service.oauth2.OAuth2GrantService;
import cn.iocoder.yudao.module.system.service.oauth2.OAuth2TokenService;
import cn.iocoder.yudao.module.system.util.oauth2.OAuth2Utils;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.Operation;
import lombok.extern.slf4j.Slf4j;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Resource;
import jakarta.annotation.security.PermitAll;
import jakarta.servlet.http.HttpServletRequest;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import static cn.iocoder.yudao.framework.common.exception.enums.GlobalErrorCodeConstants.BAD_REQUEST;
import static cn.iocoder.yudao.framework.common.exception.util.ServiceExceptionUtil.exception0;
import static cn.iocoder.yudao.framework.common.pojo.CommonResult.success;
import static cn.iocoder.yudao.framework.common.util.collection.CollectionUtils.convertList;
import static cn.iocoder.yudao.framework.security.core.util.SecurityFrameworkUtils.getLoginUserId;

/**
 * Mainly provided for external application calls
 *
 * Generally speaking, the /system-API/* of the management backend is not directly provided to external applications. The main reason is that the data and APIs that external applications can access are limited, and the RBAC of the management backend cannot be well controlled.
 * Referring to a large ID of open platforms, they all have an independent set of OpenAPI. Corresponding to [this system] is to create a new open package under the Controller, implement the /open-API/* API, and then control it through scope.
 * In addition, if a company has multiple management backends, the access tokens generated by their client_ids cannot communicate with each other, that is, they cannot access the API API of their system until the two client_ids generate trust authorization.
 *
 * Considering that [this system] does not want to make it too complicated for the time being, by default, only after obtaining the access token, you can access all APIs of /system-API/* in [this system] management background, unless scope control is manually added.
 * For examples of scope usage, see the {@link OAuth2UserController} class
 *
 * @author Yudao Source Code
 */
@Tag(name = "Management backend - OAuth2.0 authorization")
@RestController
@RequestMapping("/system/oauth2")
@Validated
@Slf4j
public class OAuth2OpenController {

    @Resource
    private OAuth2GrantService oauth2GrantService;
    @Resource
    private OAuth2ClientService oauth2ClientService;
    @Resource
    private OAuth2ApproveService oauth2ApproveService;
    @Resource
    private OAuth2TokenService oauth2TokenService;

    /**
     * Corresponds to the postAccessToken method of the TokenEndpoint class of Spring Security OAuth
     *
     * Authorization code authorization_code mode: code + redirectUri + state parameter
     * Password password mode: username + password + scope parameters
     * When refreshing refresh_token mode: refreshToken parameter
     * Client client_credentials mode: scope parameter
     * When simplifying implicit mode: not supported
     *
     * Note that client_id + client_secret parameters need to be passed by default
     */
    @PostMapping("/token")
    @PermitAll
    @Operation(summary = "Get access token", description = "Suitable for code authorization code mode, or implicit simplified mode; called by [Get] in the sso.vue single sign-in API")
    @Parameters({
            @Parameter(name = "grant_type", required = true, description = "Authorization type", example = "code"),
            @Parameter(name = "code", description = "Authorization scope", example = "userinfo.read"),
            @Parameter(name = "redirect_uri", description = "Redirect URI", example = "https://www.iocoder.cn"),
            @Parameter(name = "state", description = "Status", example = "1"),
            @Parameter(name = "username", example = "tudou"),
            @Parameter(name = "password", example = "cai"), // Use spaces to separate multiple
            @Parameter(name = "scope", example = "user_info"),
            @Parameter(name = "refresh_token", example = "123424233"),
    })
    @SuppressWarnings("EnhancedSwitchMigration")
    public CommonResult<OAuth2OpenAccessTokenRespVO> postAccessToken(HttpServletRequest request,
                                                                     @RequestParam("grant_type") String grantType,
                                                                     @RequestParam(value = "code", required = false) String code, // Authorization code mode
                                                                     @RequestParam(value = "redirect_uri", required = false) String redirectUri, // Authorization code mode
                                                                     @RequestParam(value = "state", required = false) String state, // Authorization code mode
                                                                     @RequestParam(value = "username", required = false) String username, // password mode
                                                                     @RequestParam(value = "password", required = false) String password, // password mode
                                                                     @RequestParam(value = "scope", required = false) String scope, // password mode
                                                                     @RequestParam(value = "refresh_token", required = false) String refreshToken) { // refresh mode
        List<String> scopes = OAuth2Utils.buildScopes(scope);
        // 1.1 Verify authorization type
        OAuth2GrantTypeEnum grantTypeEnum = OAuth2GrantTypeEnum.getByGrantType(grantType);
        if (grantTypeEnum == null) {
            throw exception0(BAD_REQUEST.getCode(), StrUtil.format("Unknown authorization type ({})", grantType));
        }
        if (grantTypeEnum == OAuth2GrantTypeEnum.IMPLICIT) {
            throw exception0(BAD_REQUEST.getCode(), "Token API does not support implicit authorization mode");
        }

        // 1.2 Verification client
        String[] clientIdAndSecret = obtainBasicAuthorization(request);
        OAuth2ClientDO client = oauth2ClientService.validOAuthClientFromCache(clientIdAndSecret[0], clientIdAndSecret[1],
                grantType, scopes, redirectUri);

        // 2. Obtain the access token based on the authorization mode
        OAuth2AccessTokenDO accessTokenDO;
        switch (grantTypeEnum) {
            case AUTHORIZATION_CODE:
                accessTokenDO = oauth2GrantService.grantAuthorizationCodeForAccessToken(client.getClientId(), code, redirectUri, state);
                break;
            case PASSWORD:
                accessTokenDO = oauth2GrantService.grantPassword(username, password, client.getClientId(), scopes);
                break;
            case CLIENT_CREDENTIALS:
                accessTokenDO = oauth2GrantService.grantClientCredentials(client.getClientId(), scopes);
                break;
            case REFRESH_TOKEN:
                accessTokenDO = oauth2GrantService.grantRefreshToken(refreshToken, client.getClientId());
                break;
            default:
                throw new IllegalArgumentException("Unknown authorization type:" + grantType);
        }
        Assert.notNull(accessTokenDO, "Access token cannot be empty"); // defensive check
        return success(OAuth2OpenConvert.INSTANCE.convert(accessTokenDO));
    }

    @DeleteMapping("/token")
    @PermitAll
    @Operation(summary = "Delete access token")
    @Parameter(name = "token", required = true, description = "Access Token", example = "biu")
    public CommonResult<Boolean> revokeToken(HttpServletRequest request,
                                             @RequestParam("token") String token) {
        // Verify client
        String[] clientIdAndSecret = obtainBasicAuthorization(request);
        OAuth2ClientDO client = oauth2ClientService.validOAuthClientFromCache(clientIdAndSecret[0], clientIdAndSecret[1],
                null, null, null);

        // Delete access token
        return success(oauth2GrantService.revokeToken(client.getClientId(), token));
    }

    /**
     * Corresponds to the checkToken method of the CheckTokenEndpoint class of Spring Security OAuth
     */
    @PostMapping("/check-token")
    @PermitAll
    @Operation(summary = "Verify access token")
    @Parameter(name = "token", required = true, description = "Access Token", example = "biu")
    public CommonResult<OAuth2OpenCheckTokenRespVO> checkToken(HttpServletRequest request,
                                                               @RequestParam("token") String token) {
        // Verify client
        String[] clientIdAndSecret = obtainBasicAuthorization(request);
        oauth2ClientService.validOAuthClientFromCache(clientIdAndSecret[0], clientIdAndSecret[1],
                null, null, null);

        // Verification token
        OAuth2AccessTokenDO accessTokenDO = oauth2TokenService.checkAccessToken(token);
        Assert.notNull(accessTokenDO, "Access token cannot be empty"); // defensive check
        return success(OAuth2OpenConvert.INSTANCE.convert2(accessTokenDO));
    }

    /**
     * Authorize method corresponding to the AuthorizationEndpoint class of Spring Security OAuth
     */
    @GetMapping("/authorize")
    @Operation(summary = "Obtain authorization information", description = "Suitable for code authorization code mode, or implicit simplified mode; called by [Get] in the sso.vue single sign-in API")
    @Parameter(name = "clientId", required = true, description = "client ID", example = "tudou")
    public CommonResult<OAuth2OpenAuthorizeInfoRespVO> authorize(@RequestParam("clientId") String clientId) {
        // 0. Verify that the user is logged in. Implemented via Spring Security

        // 1. Obtain client information
        OAuth2ClientDO client = oauth2ClientService.validOAuthClientFromCache(clientId);
        // 2. Obtain information that the user has authorized
        List<OAuth2ApproveDO> approves = oauth2ApproveService.getApproveList(getLoginUserId(), getUserType(), clientId);
        // Splice return
        return success(OAuth2OpenConvert.INSTANCE.convert(client, approves));
    }

    /**
     * Corresponds to the approveOrDeny method of the AuthorizationEndpoint class of Spring Security OAuth
     *
     * Scenario 1: [Automatic authorization autoApprove = true]
     *      Just enter the sso.vue API and call this API. The user history has already authorized the application accordingly, or OAuth2Client supports automatic authorization for this scope.
     * Scenario 2: [Manual authorization autoApprove = false]
     *      In the sso.vue API, the user selects the scope authorization scope and calls the API for authorization. At this time, approved is true or false
     *
     * Because the frontend and backend are separated, Axios cannot handle 302 redirection well, so it is slightly different from Spring Security OAuth. The return result is the redirected URL, and the rest is handled by the frontend.
     */
    @PostMapping("/authorize")
    @Operation(summary = "Apply for authorization", description = "Suitable for code authorization code mode, or implicit simplified mode; called by [Submit] in the sso.vue single sign-on API")
    @Parameters({
            @Parameter(name = "response_type", required = true, description = "response type", example = "code"),
            @Parameter(name = "client_id", required = true, description = "client ID", example = "tudou"),
            @Parameter(name = "scope", description = "Authorization scope", example = "userinfo.read"), // Use Map<String, Boolean> Format, Spring MVC does not currently support receiving parameters in this way.
            @Parameter(name = "redirect_uri", required = true, description = "Redirect URI", example = "https://www.iocoder.cn"),
            @Parameter(name = "auto_approve", required = true, description = "Does the user accept", example = "true"),
            @Parameter(name = "state", example = "1")
    })
    public CommonResult<String> approveOrDeny(@RequestParam("response_type") String responseType,
                                              @RequestParam("client_id") String clientId,
                                              @RequestParam(value = "scope", required = false) String scope,
                                              @RequestParam("redirect_uri") String redirectUri,
                                              @RequestParam(value = "auto_approve") Boolean autoApprove,
                                              @RequestParam(value = "state", required = false) String state) {
        @SuppressWarnings("unchecked")
        Map<String, Boolean> scopes = JsonUtils.parseObject(scope, Map.class);
        scopes = ObjectUtil.defaultIfNull(scopes, Collections.emptyMap());
        // 0. Verify that the user is logged in. Implemented via Spring Security

        // 1.1 Verify whether the responseType meets the code or token value
        OAuth2GrantTypeEnum grantTypeEnum = getGrantTypeEnum(responseType);
        // 1.2 Verify whether the redirectUri redirect domain name is legal + verify whether the scope is within the Client authorization range
        OAuth2ClientDO client = oauth2ClientService.validOAuthClientFromCache(clientId, null,
                grantTypeEnum.getGrantType(), scopes.keySet(), redirectUri);

        // 2.1 Assume approved is null, indicating that it is scenario one
        if (Boolean.TRUE.equals(autoApprove)) {
            // If automatic authorization cannot be passed, an empty URL will be returned and the front end will not jump.
            if (!oauth2ApproveService.checkForPreApproval(getLoginUserId(), getUserType(), clientId, scopes.keySet())) {
                return success(null);
            }
        } else { // 2.2 Assuming approved is not null, it means scenario 2
            // If it does not pass after calculation, jump to an error link
            if (!oauth2ApproveService.updateAfterApproval(getLoginUserId(), getUserType(), clientId, scopes)) {
                return success(OAuth2Utils.buildUnsuccessfulRedirect(redirectUri, responseType, state,
                        "access_denied", "User denied access"));
            }
        }

        // 3.1 If it is code authorization code mode, issue code authorization code and redirect
        List<String> approveScopes = convertList(scopes.entrySet(), Map.Entry::getKey, Map.Entry::getValue);
        if (grantTypeEnum == OAuth2GrantTypeEnum.AUTHORIZATION_CODE) {
            return success(getAuthorizationCodeRedirect(getLoginUserId(), client, approveScopes, redirectUri, state));
        }
        // 3.2 If it is token, it is implicit simplified mode, then send accessToken access token and redirect
        return success(getImplicitGrantRedirect(getLoginUserId(), client, approveScopes, redirectUri, state));
    }

    private static OAuth2GrantTypeEnum getGrantTypeEnum(String responseType) {
        if (StrUtil.equals(responseType, "code")) {
            return OAuth2GrantTypeEnum.AUTHORIZATION_CODE;
        }
        if (StrUtil.equalsAny(responseType, "token")) {
            return OAuth2GrantTypeEnum.IMPLICIT;
        }
        throw exception0(BAD_REQUEST.getCode(), "The response_type parameter value only allows code and token");
    }

    private String getImplicitGrantRedirect(Long userId, OAuth2ClientDO client,
                                            List<String> scopes, String redirectUri, String state) {
        // 1. Create access token access token
        OAuth2AccessTokenDO accessTokenDO = oauth2GrantService.grantImplicit(userId, getUserType(), client.getClientId(), scopes);
        Assert.notNull(accessTokenDO, "Access token cannot be empty"); // defensive check
        // 2. Splice redirected URLs
        // noinspection unchecked
        return OAuth2Utils.buildImplicitRedirectUri(redirectUri, accessTokenDO.getAccessToken(), state, accessTokenDO.getExpiresTime(),
                scopes, JsonUtils.parseObject(client.getAdditionalInformation(), Map.class));
    }

    private String getAuthorizationCodeRedirect(Long userId, OAuth2ClientDO client,
                                                List<String> scopes, String redirectUri, String state) {
        // 1. Create code authorization code
        String authorizationCode = oauth2GrantService.grantAuthorizationCodeForCode(userId, getUserType(), client.getClientId(), scopes,
                redirectUri, state);
        // 2. Splice redirected URLs
        return OAuth2Utils.buildAuthorizationCodeRedirectUri(redirectUri, authorizationCode, state);
    }

    private Integer getUserType() {
        return UserTypeEnum.ADMIN.getValue();
    }

    private String[] obtainBasicAuthorization(HttpServletRequest request) {
        String[] clientIdAndSecret = HttpUtils.obtainBasicAuthorization(request);
        if (ArrayUtil.isEmpty(clientIdAndSecret) || clientIdAndSecret.length != 2) {
            throw exception0(BAD_REQUEST.getCode(), "client_id or client_secret not passed correctly");
        }
        return clientIdAndSecret;
    }

}
