### Request /system/social-client/send-subscribe-message API => Send test subscription message
POST {{baseUrl}}/system/social-client/send-subscribe-message
Authorization: Bearer {{token}}
Content-Type: application/json
#Authorization: Bearer test100
tenant-id: {{adminTenantId}}

{
  "userId": 247,
  "userType": 1,
  "socialType": 34,
  "templateTitle": "Recharge successful notification",
  "page": "",
  "messages": {
     "character_string1":"5616122165165",
     "amount2":"1000.00",
     "time3":"2024-01-01 10:10:10",
    "phrase4": "Recharge successful"
  }
}
